#ifndef __BOARDCONFIG_H__
#define __BOARDCONFIG_H__
#include "main.h"
#define RADIO_nRESET_PIN RADIO_nRESET_Pin 
#define RADIO_nRESET_PORT RADIO_nRESET_GPIO_Port 
#define RADIO_NSS_PIN RADIO_NSS_Pin 
#define RADIO_NSS_PORT RADIO_NSS_GPIO_Port 
#define RADIO_BUSY_PIN RADIO_BUSY_Pin 
#define RADIO_BUSY_PORT RADIO_BUSY_GPIO_Port 
#define RADIO_DIOx_PIN RADIO_DIOx_Pin 
#define RADIO_DIOx_PORT RADIO_DIOx_GPIO_Port 
#define RADIO_DIO1_Pin RADIO_DIOx_Pin 
#define RADIO_DIO1_GPIO_Port RADIO_DIOx_GPIO_Port 
#define RADIO1_nRESET_PIN RADIO1_nRESET_Pin 
#define RADIO1_nRESET_PORT RADIO1_nRESET_GPIO_Port 
#define RADIO1_NSS_PIN RADIO1_NSS_Pin 
#define RADIO1_NSS_PORT RADIO1_NSS_GPIO_Port 
#define RADIO1_BUSY_PIN RADIO1_BUSY_Pin 
#define RADIO1_BUSY_PORT RADIO1_BUSY_GPIO_Port 
#define RADIO1_DIOx_PIN RADIO1_DIOx_Pin 
#define RADIO1_DIOx_PORT RADIO1_DIOx_GPIO_Port 
#define RADIO1_DIO1_Pin RADIO1_DIOx_Pin 
#define RADIO1_DIO1_GPIO_Port RADIO1_DIOx_GPIO_Port 
#endif
